name: Keep Space Alive
on:
  schedule:
    - cron: '*/15 * * * *'  # Runs every 5 minutes

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Install dependencies
        run: pip install requests
      - name: Ping Space
        run: |
          python -c "
          import requests
          try:
              response = requests.get('YOUR_SPACE_URL')
              print(f'Ping status: {response.status_code}')
          except Exception as e:
              print(f'Error: {e}')
          "